# Generated by Django 5.2.7 on 2026-08-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AudioFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("publish_date", models.DateField()),
                ("image", models.ImageField(upload_to="audio_images/")),
                ("audio_file", models.FileField(upload_to="audio_files/")),
            ],
        ),
    ]
