# Generated by Django 5.2.7 on 2026-08-26 06:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_authauditevent_verificationprofile_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="verificationchallenge",
            new_name="challenge_lookup_idx",
            old_name="catalog_ver_user_id_e8e470_idx",
        ),
        migrations.AlterUniqueTogether(
            name="purchase",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="audiofile",
            index=models.Index(fields=["category"], name="audio_category_idx"),
        ),
        migrations.AddIndex(
            model_name="audiofile",
            index=models.Index(fields=["publish_date"], name="audio_publish_date_idx"),
        ),
        migrations.AddIndex(
            model_name="audiofile",
            index=models.Index(fields=["price"], name="audio_price_idx"),
        ),
        migrations.AddIndex(
            model_name="audiofile",
            index=models.Index(
                fields=["category", "publish_date"], name="audio_category_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authauditevent",
            index=models.Index(
                fields=["user", "created_at"], name="auth_audit_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(
                fields=["user", "created_at"], name="purchase_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="verificationchallenge",
            index=models.Index(fields=["expires_at"], name="challenge_expiry_idx"),
        ),
        migrations.AddConstraint(
            model_name="audiofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gte", 0)), name="audio_price_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.UniqueConstraint(
                fields=("user", "audio_file"), name="purchase_user_audio_unique"
            ),
        ),
    ]
