# Generated by Django 5.2.7 on 2026-08-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0004_rename_catalog_ver_user_id_e8e470_idx_challenge_lookup_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="audiofile",
            index=models.Index(fields=["name"], name="audio_name_idx"),
        ),
    ]
